import fs from "fs";

const files = {
  "src/generated/prisma.ts": "export { PrismaClient } from \"../../.prisma/client/client.ts\";\nexport * from \"../../.prisma/client/client.ts\";\nexport * from \"../../.prisma/client/models.ts\";",
  "src/lib/prisma.ts": "import { PrismaClient } from \"../../.prisma/client/client.ts\";\nimport { PrismaPg } from \"@prisma/adapter-pg\";\nimport { getDbUrl } from \"../config/config.ts\";\n\nconst adapter = new PrismaPg(getDbUrl());\nexport const prisma = new PrismaClient({ adapter });",
  "src/events/events.repository.ts": "// Events repository \u2014 Prisma implementation\n\nimport { Prisma } from \"../../generated/prisma.ts\";\nimport { prisma } from \"../../lib/prisma.ts\";\nimport { Event } from \"../../domain.ts\";\nimport type { EventWhereInput } from \"../../generated/prisma.ts\";\n\nfunction toEventStringDates(event: Prisma.EventModel): Event {\n  return {\n    ...event,\n    description: event.description ?? \"\",\n    startsAt: event.startsAt.toISOString(),\n    createdAt: event.createdAt.toISOString(),\n  };\n}\n\nexport const eventsRepository = {\n  async findAll(filters?: {\n    venue?: string;\n    from?: string;\n    to?: string;\n    page?: number;\n    limit?: number;\n  }): Promise<{ data: Event[]; page: number; limit: number; total: number }> {\n    const where: EventWhereInput = {};\n\n    if (filters?.venue) {\n      where.venue = filters.venue;\n    }\n    if (filters?.from || filters?.to) {\n      where.startsAt = {};\n      if (filters.from) {\n        where.startsAt.gte = filters.from;\n      }\n      if (filters.to) {\n        where.startsAt.lte = filters.to;\n      }\n    }\n\n    const page = filters?.page ?? 1;\n    const limit = filters?.limit ?? 20;\n    const skip = (page - 1) * limit;\n\n    const [data, total] = await Promise.all([\n      prisma.event.findMany({ where, skip, take: limit, orderBy: { startsAt: \"asc\" } }),\n      prisma.event.count({ where }),\n    ]);\n\n    return { data: data.map(toEventStringDates), page, limit, total };\n  },\n\n  async findById(id: string): Promise<Event | null> {\n    const event = await prisma.event.findUnique({ where: { id } });\n    if (!event) return null;\n    return toEventStringDates(event);\n  },\n\n  async create(data: Prisma.EventCreateInput): Promise<Event> {\n    const event = await prisma.event.create({ data });\n    return toEventStringDates(event);\n  },\n\n  async update(id: string, data: Prisma.EventUpdateInput): Promise<Event | null> {\n    const event = await prisma.event.update({ where: { id }, data });\n    return toEventStringDates(event);\n  },\n\n  async delete(id: string): Promise<void> {\n    await prisma.event.delete({ where: { id } });\n  },\n};",
  "src/events/events.service.ts": "// Events service \u2014 business logic layer\n\nimport { eventsRepository } from \"../events/events.repository.ts\";\nimport { Event } from \"../domain.ts\";\nimport { AppError } from \"../middleware/error.ts\";\n\nexport const eventsService = {\n  async getAll(filters?: {\n    venue?: string;\n    from?: string;\n    to?: string;\n    page?: number;\n    limit?: number;\n  }): Promise<{ data: Event[]; page: number; limit: number; total: number }> {\n    return eventsRepository.findAll(filters);\n  },\n\n  async getById(id: string): Promise<Event | null> {\n    return eventsRepository.findById(id);\n  },\n\n  async create(\n    data: Omit<Event, \"id\" | \"createdAt\">,\n    organizerId: string\n  ): Promise<Event> {\n    return eventsRepository.create({\n      ...data,\n      organizerId,\n      createdAt: new Date().toISOString(),\n    });\n  },\n\n  async update(\n    id: string,\n    data: Partial<Event>,\n    userId: string,\n    role: string\n  ): Promise<Event | null> {\n    const event = await eventsRepository.findById(id);\n    if (!event) return null;\n\n    if (role !== \"ADMIN\" && event.organizerId !== userId) {\n      throw new AppError(403, \"Not authorized to update this event\");\n    }\n\n    return eventsRepository.update(id, data);\n  },\n\n  async delete(id: string, userId: string, role: string): Promise<boolean> {\n    const event = await eventsRepository.findById(id);\n    if (!event) return false;\n\n    if (role !== \"ADMIN\" && event.organizerId !== userId) {\n      throw new AppError(403, \"Not authorized to delete this event\");\n    }\n\n    await eventsRepository.delete(id);\n    return true;\n  },\n};"
};
for (const [file, content] of Object.entries(files)) {
  fs.writeFileSync(file, content);
  console.log("Wrote:", file);
}
