import fs from "fs";

const files = {
  "src/events/events.controller.ts": "// Events controller\n\nimport { Request, Response } from \"express\";\nimport { eventsService } from \"../events/events.service.ts\";\nimport { AppError } from \"../middleware/error.ts\";\n\nexport const eventsController = {\n  async getAll(req: Request, res: Response): Promise<void> {\n    const filters = res.locals.query as {\n      venue?: string;\n      from?: string;\n      to?: string;\n      page?: number;\n      limit?: number;\n    };\n    const result = await eventsService.getAll(filters);\n    res.json(result);\n  },\n\n  async getById(req: Request, res: Response): Promise<void> {\n    const event = await eventsService.getById(req.params.id as string);\n    if (!event) {\n      throw new AppError(404, \"Event not found\");\n    }\n    res.json(event);\n  },\n\n  async create(req: Request, res: Response): Promise<void> {\n    const event = await eventsService.create(req.body, req.auth!.sub);\n    res.status(201).json(event);\n  },\n\n  async update(req: Request, res: Response): Promise<void> {\n    const event = await eventsService.update(req.params.id as string, req.body, req.auth!.sub, req.auth!.role);\n    if (!event) {\n      throw new AppError(404, \"Event not found\");\n    }\n    res.json(event);\n  },\n\n  async delete(req: Request, res: Response): Promise<void> {\n    const deleted = await eventsService.delete(req.params.id as string, req.auth!.sub, req.auth!.role);\n    if (!deleted) {\n      throw new AppError(404, \"Event not found\");\n    }\n    res.status(204).send();\n  },\n};",
  "src/events/events.router.ts": "// Events router\n\nimport { Router } from \"express\";\nimport { eventsController } from \"../events/events.controller.ts\";\nimport { validateQuery } from \"../middleware/validateQuery.ts\";\nimport { requireAuth, requireRole } from \"../middleware/auth.ts\";\nimport { z } from \"zod\";\n\nconst router = Router();\n\nconst eventQuerySchema = z.object({\n  page: z.coerce.number().int().positive().default(1),\n  limit: z.coerce.number().int().positive().max(100).default(20),\n  venue: z.string().optional(),\n  from: z.string().datetime().optional(),\n  to: z.string().datetime().optional(),\n});\n\nconst eventCreateSchema = z.object({\n  title: z.string().min(1).max(200),\n  description: z.string().optional(),\n  venue: z.string().optional(),\n  startsAt: z.string().datetime(),\n  capacity: z.number().int().positive(),\n  priceCents: z.number().int().nonnegative(),\n});\n\nconst eventUpdateSchema = z.object({\n  title: z.string().min(1).max(200).optional(),\n  description: z.string().optional(),\n  venue: z.string().optional(),\n  startsAt: z.string().datetime().optional(),\n  capacity: z.number().int().positive().optional(),\n  priceCents: z.number().int().nonnegative().optional(),\n});\n\nrouter.get(\"/health\", (_req, res) => {\n  res.json({ status: \"ok\", uptime: process.uptime() });\n});\n\nrouter.get(\"/events\", validateQuery(eventQuerySchema), (req, res, next) =>\n  eventsController.getAll(req, res).catch(next)\n);\n\nrouter.get(\"/events/:id\", (req, res, next) =>\n  eventsController.getById(req, res).catch(next)\n);\n\nrouter.post(\n  \"/events\",\n  requireAuth,\n  requireRole(\"ORGANIZER\", \"ADMIN\"),\n  (req, res, next) => eventsController.create(req, res).catch(next)\n);\n\nrouter.patch(\n  \"/events/:id\",\n  requireAuth,\n  requireRole(\"ORGANIZER\", \"ADMIN\"),\n  (req, res, next) => eventsController.update(req, res).catch(next)\n);\n\nrouter.delete(\n  \"/events/:id\",\n  requireAuth,\n  requireRole(\"ORGANIZER\", \"ADMIN\"),\n  (req, res, next) => eventsController.delete(req, res).catch(next)\n);\n\nexport const eventsRouter = router;"
};
for (const [file, content] of Object.entries(files)) {
  fs.writeFileSync(file, content);
  console.log("Wrote:", file);
}
