import fs from "fs";

const files = {
  "src/middleware/error.ts": "// Error handling middleware\n\nimport { Request, Response, NextFunction } from \"express\";\nimport { ZodError } from \"zod\";\n\nexport class AppError extends Error {\n  constructor(\n    public status: number,\n    public message: string,\n    public details?: unknown\n  ) {\n    super(message);\n    this.name = \"AppError\";\n  }\n}\n\nexport function errorHandler(\n  err: Error,\n  _req: Request,\n  res: Response,\n  _next: NextFunction\n): void {\n  if (err instanceof ZodError) {\n    res.status(400).json({\n      error: \"Validation failed\",\n      details: err.flatten().fieldErrors,\n    });\n    return;\n  }\n\n  if (err instanceof AppError) {\n    res.status(err.status).json({ error: err.message });\n    return;\n  }\n\n  console.error(\"Unexpected error:\", err);\n  res.status(500).json({ error: \"Internal server error\" });\n}",
  "src/middleware/validate.ts": "// Zod body validation middleware\n\nimport { Request, Response, NextFunction } from \"express\";\nimport { ZodSchema } from \"zod\";\n\nexport function validate(schema: ZodSchema) {\n  return (req: Request, res: Response, next: NextFunction): void => {\n    const result = schema.safeParse(req.body);\n    if (!result.success) {\n      res.status(400).json({\n        error: \"Validation failed\",\n        details: result.error.flatten().fieldErrors,\n      });\n      return;\n    }\n    req.body = result.data;\n    next();\n  };\n}",
  "src/middleware/validateQuery.ts": "// Zod query parameter validation middleware\n\nimport { Request, Response, NextFunction } from \"express\";\nimport { ZodSchema } from \"zod\";\n\nexport function validateQuery(schema: ZodSchema) {\n  return (req: Request, res: Response, next: NextFunction): void => {\n    const result = schema.safeParse(req.query);\n    if (!result.success) {\n      res.status(400).json({\n        error: \"Validation failed\",\n        details: result.error.flatten().fieldErrors,\n      });\n      return;\n    }\n    res.locals.query = result.data;\n    next();\n  };\n}",
  "src/middleware/auth.ts": "// Authentication middleware\n\nimport { Request, Response, NextFunction } from \"express\";\nimport jwt from \"jsonwebtoken\";\nimport { env } from \"../config/config.ts\";\n\nexport interface AuthPayload {\n  sub: string;\n  role: string;\n}\n\ndeclare global {\n  namespace Express {\n    interface Request {\n      auth?: AuthPayload;\n    }\n  }\n}\n\nexport function requireAuth(\n  req: Request,\n  res: Response,\n  next: NextFunction\n): void {\n  const authHeader = req.headers.authorization;\n  if (!authHeader?.startsWith(\"Bearer \")) {\n    res.status(401).json({ error: \"Authentication required\" });\n    return;\n  }\n\n  const token = authHeader.slice(7);\n  try {\n    const payload = jwt.verify(token, env.JWT_ACCESS_SECRET, {\n      algorithms: [\"HS256\"],\n    }) as AuthPayload;\n    req.auth = payload;\n    next();\n  } catch {\n    res.status(401).json({ error: \"Invalid or expired token\" });\n  }\n}\n\nexport function requireRole(...allowedRoles: string[]) {\n  return (req: Request, res: Response, next: NextFunction): void => {\n    if (!req.auth) {\n      res.status(401).json({ error: \"Authentication required\" });\n      return;\n    }\n    if (!allowedRoles.includes(req.auth.role)) {\n      res.status(403).json({ error: \"Insufficient permissions\" });\n      return;\n    }\n    next();\n  };\n}"
};
for (const [file, content] of Object.entries(files)) {
  fs.writeFileSync(file, content);
  console.log("Wrote:", file);
}
